In [1]:
import pandas as pd

In [3]:
bg = pd.read_csv('D:\合作店铺\科帕奇\/0217_work2（sales 数据填充）.csv')

<>:1: SyntaxWarning: invalid escape sequence '\/'
<>:1: SyntaxWarning: invalid escape sequence '\/'
C:\Users\jackyzhu\AppData\Local\Temp\ipykernel_34740\336887974.py:1: SyntaxWarning: invalid escape sequence '\/'
  bg = pd.read_csv('D:\合作店铺\科帕奇\/0217_work2（sales 数据填充）.csv')

In [10]:
prod  = pd.read_csv('D:\合作店铺\科帕奇\Agg Data\科帕奇_产品分析.csv',index_col = 0)

<>:1: SyntaxWarning: invalid escape sequence '\A'
<>:1: SyntaxWarning: invalid escape sequence '\A'
C:\Users\jackyzhu\AppData\Local\Temp\ipykernel_34740\3507097067.py:1: SyntaxWarning: invalid escape sequence '\A'
  prod  = pd.read_csv('D:\合作店铺\科帕奇\Agg Data\科帕奇_产品分析.csv',index_col = 0)

In [12]:
prod = prod[prod.asin != 'Missing']

In [18]:
prod

,year,month,seller_id,marketplace,asin,Principal,FBAPerUnitFulfillmentFee,FBAWeightBasedFee,VariableClosingFee,SalesTaxCollectionFee,...,LowValueGoodsTax-Shipping,MarketplaceFacilitatorTax-Other,MarketplaceFacilitatorTax-Principal,MarketplaceFacilitatorTax-Shipping,MarketplaceFacilitatorVAT-Principal,LowValueGoodsTax-Principal,quantity_shipped,Total_Sales,Total_Fee,Total_Tax
0,2022,2,A14OQ2F4XLOPS1,Amazon.ca,B097M5Q2ZK,102.385121,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.00,0.00,0.0,0.0,1.0,102.385121,-13.510955,0.00
1,2022,2,A14OQ2F4XLOPS1,Amazon.ca,B097PBWBYJ,80.360003,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.00,0.00,0.0,0.0,1.0,80.360003,-10.859460,0.00
3,2022,2,A14OQ2F4XLOPS1,Amazon.com,B079JWBC92,585.580000,-265.500000,0.0,0.0,0.0,...,0.0,0.0,-38.52,-0.67,0.0,0.0,75.0,585.580000,-348.110000,-39.19
4,2022,2,A14OQ2F4XLOPS1,Amazon.com,B08BHV29D4,399.920000,-56.240000,0.0,0.0,0.0,...,0.0,0.0,-15.39,0.00,0.0,0.0,8.0,399.920000,-93.740000,-15.39
5,2022,2,A14OQ2F4XLOPS1,Amazon.com,B08Y8NZKWL,949.810000,-139.270000,0.0,0.0,0.0,...,0.0,0.0,-46.36,0.00,0.0,0.0,19.0,949.810000,-229.270000,-46.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31477,2024,2,A2R7HPZ408C2AG,Amazon.com,B0CHYGTZXT,145.900000,-8.930000,0.0,0.0,0.0,...,0.0,0.0,-8.75,0.00,0.0,0.0,1.0,145.900000,-26.440000,-8.75
31479,2024,2,A2R7HPZ408C2AG,Amazon.com.mx,B08MFHM54X,11.639688,-8.951904,0.0,0.0,0.0,...,0.0,0.0,0.00,0.00,0.0,0.0,1.0,11.639688,-10.348783,0.00
31480,2024,2,A2R7HPZ408C2AG,Amazon.com.mx,B0BQW2C9VF,361.020729,-26.173285,0.0,0.0,0.0,...,0.0,0.0,0.00,0.00,0.0,0.0,1.0,361.020729,-106.502853,0.00
31481,2024,2,A2R7HPZ408C2AG,Amazon.com.mx,B0CMQBLY7C,92.695322,-12.811388,0.0,0.0,0.0,...,0.0,0.0,0.00,0.00,0.0,0.0,1.0,92.695322,-33.079804,0.00
31485,2024,2,A32Z86WTB0DELB,Amazon.com,B0CH9W3XQS,1139.970000,-12.720000,0.0,0.0,0.0,...,0.0,0.0,-84.60,0.00,0.0,0.0,3.0,1139.970000,-12.720000,-84.60

In [17]:
bg[bg.asin.isin(prod.asin.unique().tolist())]

Empty DataFrame
Columns: [id, asin, region, year, month, category_root_id, category_leaf_id, rank_root, rank_leaf, rating, price, sales, create_time, update_time, review, category_name, category_root, category_leaf, lnsales, lnrank_root, lnrank_leaf, time, trueid, idid, square_rating, square_lnrank_root, square_lnrank_leaf, lnprice, lnreview, sales_zero, sales_nonzero, total_zero, total_nonzero, both, tag, lag_sales, lead_sales, avg_sales, lead2_sales, avg2_sales, rank_category_name, lnrank_category_name, lnsales_percentile, lnrank_root_percentile, lnsales_hat, lnsales_hat2]
Index: []

[0 rows x 46 columns]

In [16]:
bg

,id,asin,region,year,month,category_root_id,category_leaf_id,rank_root,rank_leaf,rating,...,lead_sales,avg_sales,lead2_sales,avg2_sales,rank_category_name,lnrank_category_name,lnsales_percentile,lnrank_root_percentile,lnsales_hat,lnsales_hat2
0,6165404,B08ZVSRCTR,US,2022,1,15684181,3147717011,2245,14,4.0,...,250.0,NaN,280.0,265.0,252.0,5.529429,88.0,3.0,4.689599,NaN
1,6165405,B08ZVSRCTR,US,2022,2,15684181,3147717011,2245,12,4.0,...,267.0,274.0,244.0,255.5,252.0,5.529429,90.0,3.0,4.758695,NaN
2,6165406,B08ZVSRCTR,US,2022,3,15684181,3147717011,2245,8,4.0,...,179.0,297.5,233.0,206.0,252.0,5.529429,92.0,3.0,4.934808,NaN
3,6165407,B08ZVSRCTR,US,2022,4,15684181,3147717011,2245,6,4.0,...,165.0,207.5,80.0,122.5,252.0,5.529429,94.0,3.0,5.030117,NaN
4,6165408,B08ZVSRCTR,US,2022,5,15684181,3147717011,2245,7,4.0,...,158.0,185.5,281.0,219.5,252.0,5.529429,94.0,3.0,5.072201,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465428,128361013,B0CMTTZGPR,US,2024,1,1055398,3733811,280848,125,4.0,...,35.0,17.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1465429,128361012,B0CMTTZGPR,US,2023,12,1055398,3733811,546187,260,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1465430,128764189,B0CMXRGXCP,US,2023,11,7141123011,679433011,239539,1958,1.0,...,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1465431,128764188,B0CMXRGXCP,US,2023,12,7141123011,679433011,494764,3287,4.0,...,0.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1465432,170469386,B0CMXRGXCP,US,2024,1,7141123011,679433011,781676,4038,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
def query_background_data(aid):        
    placeholders = ', '.join(['%s'] * len(aid))
    query = """
    SELECT asin,rating,review,rank_root,rank_leaf FROM zonglink_amazon_v9.tb_keepa_us_series
    where year = 2023 and month = 12 and asin IN ({})
    """.format(placeholders)
    params = tuple(aid)
    df = execute_query(query, params)
    cols = ['asin','亚马逊评分','亚马逊评论量','亚马逊大类排名','亚马逊小类排名']
    df = pd.DataFrame(df, columns=cols)
    query1 = """
    SELECT asin,rating,review,rank_root,rank_leaf FROM zonglink_amazon_v9.tb_keepa_eu_series
    where year = 2023 and month = 12 and asin IN ({})
    """.format(placeholders)
    df1 = execute_query(query1, params)
    df1 = pd.DataFrame(df1, columns=cols)
    res = pd.concat([df, df1], axis=0)
    return res
 
def query_category_data(aid):        
    placeholders = ', '.join(['%s'] * len(aid))
    query = """
    SELECT asin,category_root,category_leaf
    FROM zonglink_amazon_v9.tb_product_info_us
    WHERE asin IN ({})
    """.format(placeholders)
    params = tuple(aid)
    df = execute_query(query, params)
    cols = ['asin','category_root','category_leaf']
    df = pd.DataFrame(df, columns=cols)
    query1 = """
    SELECT asin,category_root,category_leaf
    FROM zonglink_amazon_v9.tb_product_info_eu
    WHERE asin IN ({})
    """.format(placeholders)
    df1 = execute_query(query1, params)
    df1 = pd.DataFrame(df1, columns=cols)
    res = pd.concat([df, df1], axis=0)
    return res
data = pd.read_excel('top5asin.xlsx')
aid = data['asin'].tolist()
category_data = query_category_data(aid)
background_data = query_background_data(aid)
has context menu


has context menu