In [1]:
import pandas as pd

In [ ]:
sql_script = """
SELECT 
    YEAR(purchase_date),
    MONTH(purchase_date),
    order_status,
    sales_channel,
    COUNT(*)
FROM
    amazon_swagger.tb_orders_v0_orders_orders
WHERE
    _seller_id IN ('A33LLDB3RRSIHG' , 'AM19TQ29Y43UA',
        'A32Z86WTB0DELB',
        'A1BEMJQXCADRU0',
        'A2FY3GQW75NO2D',
        'A2R7HPZ408C2AG',
        'AB0LFBRPZ644J',
        'A18WUWKDSC6O7I',
        'A1EUC7568MSSBK',
        'A2H4OTRAETK9S2',
        'A14OQ2F4XLOPS1',
        'A36JG63EHQR1B6',
        'A3SP2OYOU83Y6T',
        'A3419JCPA2HIT9',
        'A1AZBV6445WMJJ',
        'AEH8ZWD6QIYA',
        'AI5L06MWO4YDE',
        'A2XDLEMD14HUFW')
GROUP BY YEAR(purchase_date) , MONTH(purchase_date) , order_status,sales_channel"""

In [3]:
cancel_rate = pd.read_csv("D:\合作店铺\科帕奇\科帕奇_取消率.csv")

In [5]:
cancel_rate.columns = ['Year','Month','Status','Market','Number']

In [13]:
cancel_rate = cancel_rate.pivot(index=['Year','Month','Market'],columns='Status',values='Number').reset_index()

In [17]:
cancel_rate = cancel_rate.fillna(0)

In [18]:
cancel_rate['Total_Orders'] = cancel_rate['Canceled'] + cancel_rate['Pending'] + cancel_rate['Shipped'] + cancel_rate['Unshipped']

In [19]:
cancel_rate

Status,Year,Month,Market,Canceled,Pending,Shipped,Unshipped,Total_Orders
0,2022,2,Amazon.ca,7.0,0.0,80.0,0.0,87.0
1,2022,2,Amazon.com,78.0,0.0,1518.0,0.0,1596.0
2,2022,2,Amazon.com.mx,17.0,0.0,47.0,0.0,64.0
3,2022,3,Amazon.ca,10.0,0.0,119.0,0.0,129.0
4,2022,3,Amazon.com,117.0,0.0,1881.0,0.0,1998.0
...,...,...,...,...,...,...,...,...
70,2024,1,Amazon.com,889.0,94.0,8235.0,7.0,9225.0
71,2024,1,Amazon.com.mx,114.0,4.0,260.0,3.0,381.0
72,2024,2,Amazon.ca,26.0,7.0,270.0,15.0,318.0
73,2024,2,Amazon.com,651.0,124.0,5701.0,82.0,6558.0
74,2024,2,Amazon.com.mx,52.0,7.0,168.0,16.0,243.0

In [20]:
cancel_rate['cancel_rate'] = cancel_rate['Canceled']/cancel_rate['Total_Orders']

In [22]:
cancel_rate.to_csv('D:\合作店铺\科帕奇\Agg Data\科帕奇_订单取消率.csv')

<>:1: SyntaxWarning: invalid escape sequence '\A'
<>:1: SyntaxWarning: invalid escape sequence '\A'
C:\Users\jackyzhu\AppData\Local\Temp\ipykernel_24096\3434355092.py:1: SyntaxWarning: invalid escape sequence '\A'
  cancel_rate.to_csv('D:\合作店铺\科帕奇\Agg Data\科帕奇_订单取消率.csv')

In [23]:
cancel_rate

Status,Year,Month,Market,Canceled,Pending,Shipped,Unshipped,Total_Orders,cancel_rate
0,2022,2,Amazon.ca,7.0,0.0,80.0,0.0,87.0,0.080460
1,2022,2,Amazon.com,78.0,0.0,1518.0,0.0,1596.0,0.048872
2,2022,2,Amazon.com.mx,17.0,0.0,47.0,0.0,64.0,0.265625
3,2022,3,Amazon.ca,10.0,0.0,119.0,0.0,129.0,0.077519
4,2022,3,Amazon.com,117.0,0.0,1881.0,0.0,1998.0,0.058559
...,...,...,...,...,...,...,...,...,...
70,2024,1,Amazon.com,889.0,94.0,8235.0,7.0,9225.0,0.096369
71,2024,1,Amazon.com.mx,114.0,4.0,260.0,3.0,381.0,0.299213
72,2024,2,Amazon.ca,26.0,7.0,270.0,15.0,318.0,0.081761
73,2024,2,Amazon.com,651.0,124.0,5701.0,82.0,6558.0,0.099268
74,2024,2,Amazon.com.mx,52.0,7.0,168.0,16.0,243.0,0.213992